### ISSUE TITLE
music command doesnt work on Linux (Ubuntu 22) 

### ISSUE THREAD

**Issue by Dickgirl** [cosmo1the1god/Discord-bot-Tatsuwari-#5]
[youtube] 7XB7SiW41MU: Downloading webpage
C:/PATH_Programs/ffmpeg.exe was not found.
Exception ignored in: <function AudioSource.__del__ at 0x7f5d1c9c8160>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/disnake/player.py", line 100, in __del__
    self.cleanup()
  File "/usr/local/lib/python3.10/dist-packages/disnake/player.py", line 221, in cleanup
    self._kill_process()
  File "/usr/local/lib/python3.10/dist-packages/disnake/player.py", line 172, in _kill_process
    proc = self._process
AttributeError: 'FFmpegPCMAudio' object has no attribute '_process'

**Comment by cosmo1the1god** [comment]
Hello,
you need to install FFmpegPCMAudio separately



Am Sa., 14. Jan. 2023 um 08:52 Uhr schrieb Dickgirl <
***@***.***>:

**Comment by Dickgirl** [comment]
i need but the code doesnt work on ubuntu 22 given its calling an exe

**Comment by cosmo1the1god** [comment]
```
sudo apt install snapd
sudo apt install ffmpeg
sudo snap install ffmpeg

```

**Comment by Dickgirl** [comment]
its installed 

![image](https://user-images.githubusercontent.com/50996061/212563364-6e94c9b2-db02-4f6f-a775-7859455036dd.png)

**Comment by Dickgirl** [comment]
i had it installed the whole time
